use zed::unstable::{
    gpui::{self, AppContext as _, EventEmitter, FocusHandle, Focusable, actions},
    ui::{
        ActiveTheme as _, App, Context, InteractiveElement as _, IntoElement, ParentElement as _,
        Render, SharedString, StatefulInteractiveElement as _, Styled, Tooltip, Window, div,
        h_flex, v_flex,
    },
    workspace::{Item, Workspace},
};

actions!(palette, [OpenPalette]);

pub fn init(cx: &mut App) {
    cx.observe_new::<Workspace>(|workspace, window, cx| {
        let Some(window) = window else { return };
        let palette = cx.new(|cx| PaletteItem::new(cx));
        workspace.add_item_to_active_pane(Box::new(palette.clone()), Some(0), false, window, cx);
        workspace.register_action(move |workspace, _: &OpenPalette, window, cx| {
            workspace.add_item_to_active_pane(
                Box::new(palette.clone()),
                Some(0),
                false,
                window,
                cx,
            );
        });
    })
    .detach();
}

pub struct PaletteItem {
    focus_handle: FocusHandle,
}

impl PaletteItem {
    pub fn new(cx: &mut Context<Self>) -> Self {
        Self {
            //
            focus_handle: cx.focus_handle(),
        }
    }
}

impl Render for PaletteItem {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        div()
            //
            .bg(cx.theme().colors().background)
            .p_2()
            .child(
                //
                v_flex()
                    //
                    .gap_4()
                    .child(
                        //
                        v_flex()
                            //
                            .gap_2()
                            .child(div().text_sm().child("UI Elements"))
                            .child(
                                h_flex()
                                    //
                                    .flex_wrap()
                                    .gap_2()
                                    .child(
                                        div()
                                            .id("status-bar-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().status_bar_background)
                                            .tooltip(Tooltip::text("status_bar_background")),
                                    )
                                    .child(
                                        div()
                                            .id("title-bar-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().title_bar_background)
                                            .tooltip(Tooltip::text("title_bar_background")),
                                    )
                                    .child(
                                        div()
                                            .id("title-bar-inactive-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().title_bar_inactive_background)
                                            .tooltip(Tooltip::text(
                                                "title_bar_inactive_background",
                                            )),
                                    )
                                    .child(
                                        div()
                                            .id("toolbar-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().toolbar_background)
                                            .tooltip(Tooltip::text("toolbar_background")),
                                    )
                                    .child(
                                        div()
                                            .id("tab-bar-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().tab_bar_background)
                                            .tooltip(Tooltip::text("tab_bar_background")),
                                    )
                                    .child(
                                        div()
                                            .id("tab-inactive-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().tab_inactive_background)
                                            .tooltip(Tooltip::text("tab_inactive_background")),
                                    )
                                    .child(
                                        div()
                                            .id("tab-active-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().tab_active_background)
                                            .tooltip(Tooltip::text("tab_active_background")),
                                    )
                                    .child(
                                        div()
                                            .id("panel-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().panel_background)
                                            .tooltip(Tooltip::text("panel_background")),
                                    )
                                    .child(
                                        div()
                                            .id("panel-overlay-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().panel_overlay_background)
                                            .tooltip(Tooltip::text("panel_overlay_background")),
                                    )
                                    .child(
                                        div()
                                            .id("panel-overlay-hover-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().panel_overlay_hover)
                                            .tooltip(Tooltip::text("panel_overlay_hover")),
                                    )
                                    .child(
                                        div()
                                            .id("pane-focused-border-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().pane_focused_border)
                                            .tooltip(Tooltip::text("pane_focused_border")),
                                    )
                                    .child(
                                        div()
                                            .id("pane-group-border-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().pane_group_border)
                                            .tooltip(Tooltip::text("pane_group_border")),
                                    ),
                            ),
                    )
                    .child(
                        //
                        v_flex()
                            //
                            .gap_2()
                            .child(div().text_sm().child("Editor"))
                            .child(
                                h_flex()
                                    //
                                    .flex_wrap()
                                    .gap_2()
                                    .child(
                                        div()
                                            .id("editor-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_background)
                                            .tooltip(Tooltip::text("editor_background")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-gutter-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_gutter_background)
                                            .tooltip(Tooltip::text("editor_gutter_background")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-subheader-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_subheader_background)
                                            .tooltip(Tooltip::text("editor_subheader_background")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-active-line-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_active_line_background)
                                            .tooltip(Tooltip::text("editor_active_line_background")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-highlighted-line-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx
                                                .theme()
                                                .colors()
                                                .editor_highlighted_line_background)
                                            .tooltip(Tooltip::text(
                                                "editor_highlighted_line_background",
                                            )),
                                    )
                                    .child(
                                        div()
                                            .id("editor-line-number-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_line_number)
                                            .tooltip(Tooltip::text("editor_line_number")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-active-line-number-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_active_line_number)
                                            .tooltip(Tooltip::text("editor_active_line_number")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-hover-line-number-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_hover_line_number)
                                            .tooltip(Tooltip::text("editor_hover_line_number")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-invisible-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_invisible)
                                            .tooltip(Tooltip::text("editor_invisible")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-wrap-guide-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_wrap_guide)
                                            .tooltip(Tooltip::text("editor_wrap_guide")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-active-wrap-guide-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_active_wrap_guide)
                                            .tooltip(Tooltip::text("editor_active_wrap_guide")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-indent-guide-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_indent_guide)
                                            .tooltip(Tooltip::text("editor_indent_guide")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-indent-guide-active-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().editor_indent_guide_active)
                                            .tooltip(Tooltip::text("editor_indent_guide_active")),
                                    )
                                    .child(
                                        div()
                                            .id("editor-document-highlight-read-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx
                                                .theme()
                                                .colors()
                                                .editor_document_highlight_read_background)
                                            .tooltip(Tooltip::text(
                                                "editor_document_highlight_read_background",
                                            )),
                                    )
                                    .child(
                                        div()
                                            .id("editor-document-highlight-write-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx
                                                .theme()
                                                .colors()
                                                .editor_document_highlight_write_background)
                                            .tooltip(Tooltip::text(
                                                "editor_document_highlight_write_background",
                                            )),
                                    )
                                    .child(
                                        div()
                                            .id("editor-document-highlight-bracket-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx
                                                .theme()
                                                .colors()
                                                .editor_document_highlight_bracket_background)
                                            .tooltip(Tooltip::text(
                                                "editor_document_highlight_bracket_background",
                                            )),
                                    ),
                            ),
                    )
                    .child(
                        //
                        v_flex()
                            //
                            .gap_2()
                            .child(div().text_sm().child("Text Colors"))
                            .child(
                                h_flex()
                                    //
                                    .flex_wrap()
                                    .gap_2()
                                    .child(
                                        div()
                                            .id("text-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().text)
                                            .tooltip(Tooltip::text("text")),
                                    )
                                    .child(
                                        div()
                                            .id("text-muted-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().text_muted)
                                            .tooltip(Tooltip::text("text_muted")),
                                    )
                                    .child(
                                        div()
                                            .id("text-placeholder-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().text_placeholder)
                                            .tooltip(Tooltip::text("text_placeholder")),
                                    )
                                    .child(
                                        div()
                                            .id("text-disabled-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().text_disabled)
                                            .tooltip(Tooltip::text("text_disabled")),
                                    )
                                    .child(
                                        div()
                                            .id("text-accent-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().text_accent)
                                            .tooltip(Tooltip::text("text_accent")),
                                    ),
                            ),
                    )
                    .child(
                        //
                        v_flex()
                            //
                            .gap_2()
                            .child(div().text_sm().child("Icons"))
                            .child(
                                h_flex()
                                    //
                                    .flex_wrap()
                                    .gap_2()
                                    .child(
                                        div()
                                            .id("icon-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().icon)
                                            .tooltip(Tooltip::text("icon")),
                                    )
                                    .child(
                                        div()
                                            .id("icon-muted-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().icon_muted)
                                            .tooltip(Tooltip::text("icon_muted")),
                                    )
                                    .child(
                                        div()
                                            .id("icon-disabled-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().icon_disabled)
                                            .tooltip(Tooltip::text("icon_disabled")),
                                    )
                                    .child(
                                        div()
                                            .id("icon-placeholder-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().icon_placeholder)
                                            .tooltip(Tooltip::text("icon_placeholder")),
                                    )
                                    .child(
                                        div()
                                            .id("icon-accent-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().icon_accent)
                                            .tooltip(Tooltip::text("icon_accent")),
                                    ),
                            ),
                    )
                    .child(
                        //
                        v_flex()
                            //
                            .gap_2()
                            .child(div().text_sm().child("Borders"))
                            .child(
                                h_flex()
                                    //
                                    .flex_wrap()
                                    .gap_2()
                                    .child(
                                        div()
                                            .id("border-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().border)
                                            .tooltip(Tooltip::text("border")),
                                    )
                                    .child(
                                        div()
                                            .id("border-variant-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().border_variant)
                                            .tooltip(Tooltip::text("border_variant")),
                                    )
                                    .child(
                                        div()
                                            .id("border-focused-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().border_focused)
                                            .tooltip(Tooltip::text("border_focused")),
                                    )
                                    .child(
                                        div()
                                            .id("border-selected-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().border_selected)
                                            .tooltip(Tooltip::text("border_selected")),
                                    )
                                    .child(
                                        div()
                                            .id("border-transparent-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().border_transparent)
                                            .tooltip(Tooltip::text("border_transparent")),
                                    )
                                    .child(
                                        div()
                                            .id("border-disabled-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().border_disabled)
                                            .tooltip(Tooltip::text("border_disabled")),
                                    ),
                            ),
                    )
                    .child(
                        //
                        v_flex()
                            //
                            .gap_2()
                            .child(div().text_sm().child("Backgrounds"))
                            .child(
                                h_flex()
                                    //
                                    .flex_wrap()
                                    .gap_2()
                                    .child(
                                        div()
                                            .id("elevated-surface-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().elevated_surface_background)
                                            .tooltip(Tooltip::text("elevated_surface_background")),
                                    )
                                    .child(
                                        div()
                                            .id("surface-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().surface_background)
                                            .tooltip(Tooltip::text("surface_background")),
                                    )
                                    .child(
                                        div()
                                            .id("element-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().element_background)
                                            .tooltip(Tooltip::text("element_background")),
                                    )
                                    .child(
                                        div()
                                            .id("element-hover-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().element_hover)
                                            .tooltip(Tooltip::text("element_hover")),
                                    )
                                    .child(
                                        div()
                                            .id("element-active-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().element_active)
                                            .tooltip(Tooltip::text("element_active")),
                                    )
                                    .child(
                                        div()
                                            .id("element-selected-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().element_selected)
                                            .tooltip(Tooltip::text("element_selected")),
                                    )
                                    .child(
                                        div()
                                            .id("element-selection-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().element_selection_background)
                                            .tooltip(Tooltip::text("element_selection_background")),
                                    )
                                    .child(
                                        div()
                                            .id("element-disabled-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().element_disabled)
                                            .tooltip(Tooltip::text("element_disabled")),
                                    )
                                    .child(
                                        div()
                                            .id("drop-target-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().drop_target_background)
                                            .tooltip(Tooltip::text("drop_target_background")),
                                    )
                                    .child(
                                        div()
                                            .id("drop-target-border-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().drop_target_border)
                                            .tooltip(Tooltip::text("drop_target_border")),
                                    )
                                    .child(
                                        div()
                                            .id("ghost-element-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().ghost_element_background)
                                            .tooltip(Tooltip::text("ghost_element_background")),
                                    )
                                    .child(
                                        div()
                                            .id("ghost-element-hover-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().ghost_element_hover)
                                            .tooltip(Tooltip::text("ghost_element_hover")),
                                    )
                                    .child(
                                        div()
                                            .id("ghost-element-active-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().ghost_element_active)
                                            .tooltip(Tooltip::text("ghost_element_active")),
                                    )
                                    .child(
                                        div()
                                            .id("ghost-element-selected-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().ghost_element_selected)
                                            .tooltip(Tooltip::text("ghost_element_selected")),
                                    )
                                    .child(
                                        div()
                                            .id("ghost-element-disabled-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().ghost_element_disabled)
                                            .tooltip(Tooltip::text("ghost_element_disabled")),
                                    ),
                            ),
                    )
                    .child(
                        //
                        v_flex()
                            //
                            .gap_2()
                            .child(div().text_sm().child("Terminal"))
                            .child(
                                h_flex()
                                    //
                                    .flex_wrap()
                                    .gap_2()
                                    .child(
                                        div()
                                            .id("terminal-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_background)
                                            .tooltip(Tooltip::text("terminal_background")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-foreground-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_foreground)
                                            .tooltip(Tooltip::text("terminal_foreground")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-bright-foreground-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_bright_foreground)
                                            .tooltip(Tooltip::text("terminal_bright_foreground")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-dim-foreground-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_dim_foreground)
                                            .tooltip(Tooltip::text("terminal_dim_foreground")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-background-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_background)
                                            .tooltip(Tooltip::text("terminal_ansi_background")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-black-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_black)
                                            .tooltip(Tooltip::text("terminal_ansi_black")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-bright-black-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_bright_black)
                                            .tooltip(Tooltip::text("terminal_ansi_bright_black")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-dim-black-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_dim_black)
                                            .tooltip(Tooltip::text("terminal_ansi_dim_black")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-red-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_red)
                                            .tooltip(Tooltip::text("terminal_ansi_red")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-bright-red-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_bright_red)
                                            .tooltip(Tooltip::text("terminal_ansi_bright_red")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-dim-red-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_dim_red)
                                            .tooltip(Tooltip::text("terminal_ansi_dim_red")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-green-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_green)
                                            .tooltip(Tooltip::text("terminal_ansi_green")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-bright-green-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_bright_green)
                                            .tooltip(Tooltip::text("terminal_ansi_bright_green")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-dim-green-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_dim_green)
                                            .tooltip(Tooltip::text("terminal_ansi_dim_green")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-yellow-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_yellow)
                                            .tooltip(Tooltip::text("terminal_ansi_yellow")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-bright-yellow-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_bright_yellow)
                                            .tooltip(Tooltip::text("terminal_ansi_bright_yellow")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-dim-yellow-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_dim_yellow)
                                            .tooltip(Tooltip::text("terminal_ansi_dim_yellow")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-blue-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_blue)
                                            .tooltip(Tooltip::text("terminal_ansi_blue")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-bright-blue-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_bright_blue)
                                            .tooltip(Tooltip::text("terminal_ansi_bright_blue")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-dim-blue-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_dim_blue)
                                            .tooltip(Tooltip::text("terminal_ansi_dim_blue")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-magenta-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_magenta)
                                            .tooltip(Tooltip::text("terminal_ansi_magenta")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-bright-magenta-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_bright_magenta)
                                            .tooltip(Tooltip::text("terminal_ansi_bright_magenta")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-dim-magenta-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_dim_magenta)
                                            .tooltip(Tooltip::text("terminal_ansi_dim_magenta")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-cyan-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_cyan)
                                            .tooltip(Tooltip::text("terminal_ansi_cyan")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-bright-cyan-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_bright_cyan)
                                            .tooltip(Tooltip::text("terminal_ansi_bright_cyan")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-dim-cyan-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_dim_cyan)
                                            .tooltip(Tooltip::text("terminal_ansi_dim_cyan")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-white-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_white)
                                            .tooltip(Tooltip::text("terminal_ansi_white")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-bright-white-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_bright_white)
                                            .tooltip(Tooltip::text("terminal_ansi_bright_white")),
                                    )
                                    .child(
                                        div()
                                            .id("terminal-ansi-dim-white-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().terminal_ansi_dim_white)
                                            .tooltip(Tooltip::text("terminal_ansi_dim_white")),
                                    ),
                            ),
                    )
                    .child(
                        //
                        v_flex()
                            //
                            .gap_2()
                            .child(div().text_sm().child("Version Control"))
                            .child(
                                h_flex()
                                    //
                                    .flex_wrap()
                                    .gap_2()
                                    .child(
                                        div()
                                            .id("version-control-added-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().version_control_added)
                                            .tooltip(Tooltip::text("version_control_added")),
                                    )
                                    .child(
                                        div()
                                            .id("version-control-deleted-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().version_control_deleted)
                                            .tooltip(Tooltip::text("version_control_deleted")),
                                    )
                                    .child(
                                        div()
                                            .id("version-control-modified-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().version_control_modified)
                                            .tooltip(Tooltip::text("version_control_modified")),
                                    )
                                    .child(
                                        div()
                                            .id("version-control-renamed-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().version_control_renamed)
                                            .tooltip(Tooltip::text("version_control_renamed")),
                                    )
                                    .child(
                                        div()
                                            .id("version-control-conflict-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().version_control_conflict)
                                            .tooltip(Tooltip::text("version_control_conflict")),
                                    )
                                    .child(
                                        div()
                                            .id("version-control-ignored-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().version_control_ignored)
                                            .tooltip(Tooltip::text("version_control_ignored")),
                                    )
                                    .child(
                                        div()
                                            .id("version-control-word-added-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().version_control_word_added)
                                            .tooltip(Tooltip::text("version_control_word_added")),
                                    )
                                    .child(
                                        div()
                                            .id("version-control-word-deleted-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx.theme().colors().version_control_word_deleted)
                                            .tooltip(Tooltip::text("version_control_word_deleted")),
                                    )
                                    .child(
                                        div()
                                            .id("version-control-conflict-marker-ours-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx
                                                .theme()
                                                .colors()
                                                .version_control_conflict_marker_ours)
                                            .tooltip(Tooltip::text(
                                                "version_control_conflict_marker_ours",
                                            )),
                                    )
                                    .child(
                                        div()
                                            .id("version-control-conflict-marker-theirs-square")
                                            .w_8()
                                            .h_8()
                                            .bg(cx
                                                .theme()
                                                .colors()
                                                .version_control_conflict_marker_theirs)
                                            .tooltip(Tooltip::text(
                                                "version_control_conflict_marker_theirs",
                                            )),
                                    ),
                            ),
                    ),
            )
    }
}

pub enum PaletteEvent {}
impl EventEmitter<PaletteEvent> for PaletteItem {}
impl Focusable for PaletteItem {
    fn focus_handle(&self, _cx: &App) -> FocusHandle {
        self.focus_handle.clone()
    }
}

impl Item for PaletteItem {
    type Event = PaletteEvent;

    fn tab_content_text(&self, _detail: usize, _cx: &App) -> SharedString {
        "Theme Palette".into()
    }
}
